//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RussloWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RussloWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [
        ///  {
        ///    &quot;Author&quot;: &quot;М.Б. Жемчугова, Н.И.Романова&quot;,
        ///    &quot;Title&quot;: &quot;Биология. 8 класс. НЕ ПРОДАЁТСЯ!&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;Author&quot;: &quot;Е.А. Быстрова, Л.В. Кибирева и др.&quot;,
        ///    &quot;Title&quot;: &quot;Русский язык. 9 класс. Часть 1&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;Author&quot;: &quot;В.А. Чалмаев, С.А. Зинин&quot;,
        ///    &quot;Title&quot;: &quot;Литература. 11 класс. Часть 1. Базовый уровень&quot;,
        ///    &quot;Description&quot;: &quot;&quot;
        ///  },
        ///  {
        ///    &quot;Author&quot;: &quot;А.В. Королёв&quot;,
        ///    &quot;Title&quot;: &quot;«Каштанка» А.П. Чехова&quot;,
        ///    &quot;Description&quot;: &quot;Видеол [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BooksList {
            get {
                return ResourceManager.GetString("BooksList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;title&gt;Title&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;width: 600px; height: 800px; padding: 30px;&quot;&gt;
        ///        &lt;h1&gt;{0}&lt;/h1&gt;
        ///        &lt;h2&gt;{1}&lt;/h2&gt;
        ///        &lt;p&gt;{2}&lt;/p&gt;
        ///        &lt;img width=&quot;229&quot; height=&quot;320&quot; src=&quot;data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/4QAqRXhpZgAASUkqAAgAAAABADEBAgAHAAAAGgAAAAAAAABHb29nbGUAAP/bAIQAAwICCgoLCwoKCggKCgoKCwsLCAoKCgoLCgoICgoKCgoKCgoKCwoKCgoICgoKCwoKCgoK [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ReaderStub {
            get {
                return ResourceManager.GetString("ReaderStub", resourceCulture);
            }
        }
    }
}
